### ISSUE TITLE
SharedPreferences Placeholder instead of SharedPreferences

### ISSUE THREAD

**Issue by felixgabler** [DavBfr/flutter_pref#1]
With the Null Safety, you introduced a placeholder object for SharedPreferences:
https://github.com/DavBfr/flutter_pref/blob/45ad35d160ee44cb7753d60a1f3053a6b75d1c47/pref/lib/src/service/shared_preferences.dart#L12

**Comment by DavBfr** [comment]
Yes, you're right! That was because SharedPreferences was not yet null-safe. I'll fix that.

**Comment by DavBfr** [comment]
Published version 2.0.0.
