### ISSUE TITLE
[Feature Request] Show use across multiple pages in example or another example

### ISSUE THREAD

**Issue by ciphersage** [DavBfr/flutter_pref#12]
I'm wondering if it is possible to modify or add new example to show use of this code across more than one page. I have an application that could benefit from this project, but the preferences are organized in several pages, not just one home page.

**Comment by MrCsabaToth** [comment]
My app has 7 pages of preferences, unfortunately closed source as of now. My take: I created a common base class (unlike some cancel culture around OOP principles like inheritance it can be indeed useful) for the preference page which takes care of common tasks and appearance. It ended up being pretty lean, you may grab the pref instance from whatever framework you use for state handling, and I also have some common validation functions across several pages which I host in the base class. Then I have a Hub class which enumerates all the pages descending from that page base class. The user gets to the hub first when clicking on the preferences gear, and then can navigate to actual preferences pages which cover different preference areas. Sorry if this is too abstract, maybe one day my app will be open source.

**Comment by ciphersage** [comment]
Many thanks MrCsabaToth, yes this helps. I think I do follow your logic and will try to implement a similar scheme on my project.

**Comment by MrCsabaToth** [comment]
This could be still a valid ticket, a tad out of scope but someone may develop an example...
