### ISSUE TITLE
PrefSwitch behaviour/rendering

### ISSUE THREAD

**Issue by adrianvintu** [DavBfr/flutter_pref#16]
Hello, I do not understand this iOS bug.

On iPhone 12 mini 15.1 the `PrefSwitch` is rendered in green when the accent color is pink-ish.

I have tried to create a simple Checkbox and it looks totally different than `PrefSwitch`.

What kind of magic is happening?

![PrefSwitch](https://user-images.githubusercontent.com/33379688/144742808-0ec671b5-e8b7-4c89-ae30-12ae966c187d.png)

This is the rendering on Android:

![PrefSwitch android](https://user-images.githubusercontent.com/33379688/144743054-8e193c63-45e2-4b57-9a88-8b16f0f3c247.png)

**Comment by DavBfr** [comment]
can be the difference between accentColor and colorTheme.secondary?

**Comment by DavBfr** [comment]
I added `adaptive` property to the PrefSwitch widget you can use to disable this.

**Comment by adrianvintu** [comment]
Thank you!
