### ISSUE TITLE
[Feature] Add Color Picker

### ISSUE THREAD

**Issue by ThexXTURBOXx** [DavBfr/flutter_pref#17]
There are packages like [flutter_colorpicker](https://pub.dev/packages/flutter_colorpicker) which could allow for additional config options like a color picker.
If not possible, I might create an extension package myself :)

**Comment by DavBfr** [comment]
Yes, that's a good addition. I don't like the idea to force a specific package though, it's too opinionated.
Instead, we can have a widget that takes some callbacks to get/set the value from a user-defined widget.

```dart
PrefCustom({
    String pref,
    Widget? title,
    Widget? subtitle,
    dynamic Function(value) onTap,
    Widget Function(value) child,
  });
```

You'd use that with the child to display the current color value, and onTap would return the new value.

**Comment by ThexXTURBOXx** [comment]
Yeah, I already thought that forcing the package would be a bad decision.
However, the `PrefCustom` widget sounds nice for such cases!
Whenever there is a test version available (if wanted even only on `git` without a full release), I could also give feedback.
Thank you very much for your fast response, also! :)

**Comment by DavBfr** [comment]
Here: https://github.com/DavBfr/flutter_pref/blob/master/pref/example/lib/custom.dart

**Comment by ThexXTURBOXx** [comment]
Thank you very much for your work! This works perfectly! :)
I will close this issue as this will be fixed in the next release. Thank you again for your fast work!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).
