### ISSUE TITLE
The need for a `set` function which returns a `Future` so `then` can be used

### ISSUE THREAD

**Issue by RoarGronmo** [DavBfr/flutter_pref#19]
I have found a situation where I cannot use `addKeyListener` to trigger when `set` is being used to mimick a `then` function.

Normally when `Future`s are used, I can use `then` to trigger an action when the `Future` is returned. 

Not so with `FutureOr` which is used as returning value for the `set` function.

If I then have a function which sets the value with another `set` from elsewhere the `addKeyListener` catches it which may be unintended. (I just want to change the value without triggering a secondary action).

Or do you have an other approach which I have not seen yet ?

**Comment by DavBfr** [comment]
Usually, you don't have to wait for the return value of `set()` it's there only if you want to be sure the backend has actually saved the data (e.g. on disk).
