### ISSUE TITLE
How to get pref value from PrefService in ChangeNotifier

### ISSUE THREAD

**Issue by hntan** [DavBfr/flutter_pref#2]
With the [preferences](https://pub.dev/packages/preferences) package, I simple use PrefService.get('somekey') anywhere but could not any more with flutter_pref.

Bellow is my code:

```
import 'package:flutter/material.dart';
import 'package:pref/pref.dart';

class BottomNavigationBarProvider with ChangeNotifier {
  int _currentIndex = 2;

  BottomNavigationBarProvider() {
    String startPage = PrefService.of(????).get('START_PAGE');

    switch (startPage) {
      case 'PAGE_1':
        _currentIndex = 0;
        break;
      case 'PAGE_2':
        _currentIndex = 2;
        break;
      case 'HOME':
      default:
        _currentIndex = 1;
        break;
    }
  }

  get currentIndex => _currentIndex;

  set currentIndex(int index) {
    _currentIndex = index;
    notifyListeners();
  }
}
```

And this is my main.dart

```void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final service = await PrefServiceShared.init(
    defaults: {
      'START_PAGE': 1,
    }
  );
```

**Comment by DavBfr** [comment]
You have to pass a BuildContext to PrefService.of().

**Comment by MrCsabaToth** [comment]
But I want to use `PrefService` in business logic. Why for the love of God does the API punish with this context thing? I'd want to migrate from https://pub.dev/packages/preferences where I can simply say `PrefService.getBool('anywhere')` ANYWHERE I want. Also note that there's synchronous API, so I don't have to do any magic tricks if I want to read a preferences in `initState`, which is how it should be. My reads / writes are mostly in business logic or at most `initState`. But I don't mess around with preferences in build code.

**Comment by DavBfr** [comment]
@MrCsabaToth the `preferences` package used some global variables, which is bad. This library takes a different approach, a lot more powerful, and testable.
The `PrefService` object can store data anywhere, can be in shared preferences, or on firebase, or your own storage.
Using a context allow using different storage mechanism in you app, depending on where you are.
If you prefer `preferences`, keep it, why the change?

**Comment by MrCsabaToth** [comment]
> @MrCsabaToth the `preferences` package used some global variables, which is bad. This library takes a different approach, a lot more powerful, and testable.
> The `PrefService` object can store data anywhere, can be in shared preferences, or on firebase, or your own storage.
> Using a context allow using different storage mechanism in you app, depending on where you are.
> If you prefer `preferences`, keep it, why the change?

I see. Multiple reasons: it's discontinued and for example it doesn't support integer preferences like your package with the sliders. So if I'd just want to use shared preferences can I just fabricate a context somehow which would tell your logic to use shared preferences?

**Comment by DavBfr** [comment]
I didn't know it was discontinued.

It's a Flutter `BuildContext` object. It works like Provider.

**Comment by MrCsabaToth** [comment]
> I didn't know it was discontinued.
> 
> It's a Flutter `BuildContext` object. It works like Provider.

Hmmm, I didn't realize that `PrefService` is a Widget. I'm looking at the example. Can I get away with somehow only using `BasePrefService` when I'm in a business logic or context-less code section? I'm using Get (https://pub.dev/packages/get) so I can just register an instance of it and roll?

**Comment by DavBfr** [comment]
I guess you can inject your PrefService into get and consider it as a dependency.

**Comment by MrCsabaToth** [comment]
Since a Widget is a UI part I'd be extremely hesitant to basically cache one (when I'd register it to Get it'd be almost like a global variable), what happens if I navigate to a different screen? I'm thinking of defining a class which represents all my settings, that would be updated when the preferences screen is on display and I could poll that object in other portions of the app. But in one way or another you could look at that as a global variable. And I'd need to solve a few places which update the preferences outside of the explicit preferences screen.

**Comment by DavBfr** [comment]
No, don't cache the Widget, but the instance of PrefServiceShared instead, which can be a global with no issues.

**Comment by MrCsabaToth** [comment]
> No, don't cache the Widget, but the instance of PrefServiceShared instead, which can be a global with no issues.

Thanks, makes sense!

**Comment by DavBfr** [comment]
Don't hesitate to [Buy Me A Coffee](https://www.buymeacoffee.com/JORBmbw9h).

**Comment by tneotia** [comment]
@MrCsabaToth if you use Getx (I do too) you can simply use `Get.context` in place of `BuildContext`. This does require your initial widget to be `GetMaterialApp` instead of `MaterialApp`. Works great in my app!

**Comment by MrCsabaToth** [comment]
> @MrCsabaToth if you use Getx (I do too) you can simply use `Get.context` in place of `BuildContext`. This does require your initial widget to be `GetMaterialApp` instead of `MaterialApp`. Works great in my app!

Thanks Tanay, this is a life saver!!!
