### ISSUE TITLE
`PrefService.of(context).set` may cause some kind of redraw or reinit of application

### ISSUE THREAD

**Issue by RoarGronmo** [DavBfr/flutter_pref#21]
Strange incident when I am setting values like this:

```
                            PrefService.of(context).set(SettingKey.userCountryCode, countries[index].ctryNo.toString());
                            PrefService.of(context).set(SettingKey.userFirmNo, "-1");
                            PrefService.of(context).set(SettingKey.userOfficeNo, "-1");
```

...my widget or app then suddenly get restarted (like setting a new state).

This happens also when entering the settings page an tries to change a value there.

I haven't set any listeners...

**Comment by DavBfr** [comment]
When you call PrefService.of(context) it automatically registers an event listener for this widget and updates it whenever something changes.
If you don't want that, call it with listen=false:

```dart
PrefService.of(context, listen=false)
  ..set(SettingKey.userCountryCode, countries[index].ctryNo.toString())
  ..set(SettingKey.userFirmNo, "-1")
  ..set(SettingKey.userOfficeNo, "-1");
```

**Comment by RoarGronmo** [comment]
::This happens also when entering the settings page an tries to change a value there.

BTW: How do I prevent that when making changes on the settingpage ?

**Comment by DavBfr** [comment]
You can use cache=true on the PrefPage Widget. That will prevent any change from propagating in real-time, but only when you close the settings page.
