### ISSUE TITLE
PrefColor not found

### ISSUE THREAD

**Issue by asamoylenko8000** [DavBfr/flutter_pref#22]
I use 'pref 2.6.0' and prefColor not extsts in this version, but example shows us, how we can it use.

**Comment by DavBfr** [comment]
Yes, this widget does not exist, but you can copy this one based on PrefCustom to implement it.
https://github.com/DavBfr/flutter_pref/blob/master/pref/example/lib/custom.dart

The reason it's not provided is to allow you to use any color picker you want.

**Comment by asamoylenko8000** [comment]
Thank's. It works fine.
