### ISSUE TITLE
Feature request: integer preferences with additional spinner up / down buttons

### ISSUE THREAD

**Issue by MrCsabaToth** [DavBfr/flutter_pref#25]
Sometimes the input range of an integer is so large that a slider is not feasible. In that case it'd be great to have a integer value edit with additional up and down buttons to increment and decrement the value. Maybe optionally additional fast up / down buttons which subtract or add 10 or larger increments at a time.

**Comment by DavBfr** [comment]
Implemented as an [example](https://github.com/DavBfr/flutter_pref/blob/2948b5d4d62c6f42d95eb001db43318001c90ac3/pref/example/lib/custom.dart#L72) in version 2.7.0
