### ISSUE TITLE
Handling of integer preference with PrefText

### ISSUE THREAD

**Issue by bernd70** [DavBfr/flutter_pref#29]
Is there a way, to handle integer preferences with PrefText?

I can set the KeyboardType and InputFormatters as required but PrefText seems not to be able to load/save an int value.

I do not want to use a slider or the NumberSelector control.

Is there a chance that pref will support int only in PrefText od do I have to write a custom control?

Bernd

**Comment by DavBfr** [comment]
Writing a custom widget is pretty easy. Here is an example:
https://github.com/DavBfr/flutter_pref/blob/master/pref/example/lib/custom.dart#L72

If you want to create one for integers based on a text entry, you can provide a PR.

**Comment by bernd70** [comment]
Thank you for the example. Sounds pretty straigtforward even for sombody just playing around a couple of days with flutter... :-)

I will try to build it and contribute as a PR.

**Comment by bernd70** [comment]
David, I did implement PrefIntegerText but never did a PR with GitHub. I cloned your repo and implemented it there but how do a make the PR now?

**Comment by DavBfr** [comment]
You should have a button on your GitHub page to create the PR.
I don't see the fork on your GitHub page, maybe it has to be public to allow PRs.

**Comment by bernd70** [comment]
I cloned your repo instead of forking it. Now with a fork I was able to create the pull request.
