### ISSUE TITLE
`ProxyPrefService` is missing implementations for theese members

### ISSUE THREAD

**Issue by RoarGronmo** [DavBfr/flutter_pref#34]
After upgrading flutter beta channel to: 
```
Flutter 3.15.0-15.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b2ec15bfa3 (3 days ago) • 2023-09-14 15:31:44 -0500
Engine • revision 5c86194494
Tools • Dart 3.2.0 (build 3.2.0-134.1.beta) • DevTools 2.27.0
```

The build fails with following error: 
```
[+4397 ms] /C:/Users/roarg/AppData/Local/Pub/Cache/hosted/pub.dev/pref-2.7.1/lib/src/service/proxy.dart:12:7: Error: The non-abstract class 'ProxyPrefService' is missing implementations for these members:
[   +1 ms]  - ChangeNotifier.maybeDispatchObjectCreation
[        ] Try to either
[        ]  - provide an implementation,
[        ]  - inherit an implementation from a superclass or mixin,
[        ]  - mark the class as abstract, or
[        ]  - provide a 'noSuchMethod' implementation.
[        ] class ProxyPrefService with DiagnosticableTreeMixin implements BasePrefService {
[        ]       ^^^^^^^^^^^^^^^^
[        ] /c:/Flutter/flutter/packages/flutter/lib/src/foundation/change_notifier.dart:230:8: Context: 'ChangeNotifier.maybeDispatchObjectCreation' is defined here.
[        ]   void maybeDispatchObjectCreation() {
[        ]        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Can you update 'pref' library with the changes suggested ?

**Comment by MrCsabaToth** [comment]
Check out my PR

**Comment by nohkumado** [comment]
hitting the same problem.... 
a little howto on how to add the github version into the pubspec would be welcome, i tried: 
```
   pref: 
      git:
        url: git@github.com:DavBfr/flutter_pref.git
```

but this fails with 

```Could not find a file named "pubspec.yaml" in git@github.com:DavBfr/flutter_pref.git 0743081a0ef063f4db06395e23b5b32dfd3f3272.```

**Comment by DavBfr** [comment]
you need to add a path:

```yaml
 pref:
      git:
        url: git@github.com:DavBfr/flutter_pref.git
        path: pref
```

**Comment by MrCsabaToth** [comment]
Relevant news: after upgrading to the newest Flutter SDK beta `3.16.0-0.1.pre` (tooling `2.28.1`), the `maybeDispatchObjectCreation` is not needed, so essentially my PR is not needed. To be more precise my PR causes compilation error with the newest beta. So the best solution to this issue right now after upgrading to `3.16.0-0.1.pre` is to simply use the official `2.7.1` pref. If the beta SDK stays this way my PR needs to be undone (the beta channel test needs to be undone possibly anyway).

**Comment by MrCsabaToth** [comment]
I created a PR https://github.com/DavBfr/flutter_pref/pull/36 for undoing my earlier PR, but let's wait until the next stable and beta SDK to see if the changes stay like that.
