### ISSUE TITLE
logging can not be disabled

### ISSUE THREAD

**Issue by ashemetov** [DavBfr/flutter_pref#6]
Package logs every change, it my case I store game state every second, so package is logging too much. Didn't find a way to disable it or set logging level, because of that debugging is not very convenient.

**Comment by DavBfr** [comment]
Please try the master branch

**Comment by ashemetov** [comment]
Confirmed, working fine, will wait for release of version 2.2.0

**Comment by DavBfr** [comment]
Let's go then!
