### ISSUE TITLE
Cannot set null values in PrefService

### ISSUE THREAD

**Issue by tneotia** [DavBfr/flutter_pref#8]
It seems the `PrefService` will not let me set null values - I remember it was working earlier but now my entire app is broken because of this. If I do `var result = await PrefService.of(context).set<String?>("test", null);` then result comes out `false` instead of `true`.

Is this intentional design?

**Comment by DavBfr** [comment]
It's not necessarily intentional. Some leftover from null-safety migration. I'll check that.

**Comment by DavBfr** [comment]
This library supports null values, but the underlying library [shared_preferences ](https://pub.dev/packages/shared_preferences) doesn't aparently.

**Comment by tneotia** [comment]
Yep.. after some experimenting I found that the `.remove` method does the trick. If you'd like to keep it this way I would suggest changing the API design to prevent nullable types from being set using `.set` to avoid confusing users.

**Comment by DavBfr** [comment]
Fixed in version 2.3.0
