### ISSUE TITLE
Slider is too short while it is in a row with the label

### ISSUE THREAD

**Issue by MrCsabaToth** [DavBfr/flutter_pref#9]
I'd propose to have the label and the slider laid out in a `Column` instead of the `Row`. Otherwise the slider is way too narrow for example to set a weight or age of a person.

**Comment by DavBfr** [comment]
Yes, good point. Could be a new parameter in the constructor: `Axis direction = Axis.horizontal,` to give the choice, with backward compatibility.
Can you implement it and provide a PR?

**Comment by MrCsabaToth** [comment]
> Yes, good point. Could be a new parameter in the constructor: `Axis direction = Axis.horizontal,` to give the choice, with backward compatibility.
> Can you implement it and provide a PR?

I certainly will devise a PR. I was thinking of a `bool inline` setting which would be true by default. I'll test this on mobile, I'd want to keep the trailing and the title in the same row, and put the slider bellow those two if the `inline` is false. I'll also think about the subtitle.
